-- Autogenerated by util/gen-luatags.pl, do not edit.

------------------------------------------------------------------------------
-- tags.lua:
-- Tag and version compatibility functions and info.
------------------------------------------------------------------------------
tags = {}

------------------------------------------------------------------------------
-- simpler access to tag_major_version
------------------------------------------------------------------------------

function tags.major_version ()
  return file.major_version()
end

tags.TAG_MINOR_RESET = 0
tags.TAG_MINOR_BRANCHES_LEFT = 1
tags.TAG_MINOR_VAULT_LIST = 2
tags.TAG_MINOR_TRAPS_DETERM = 3
tags.TAG_MINOR_ACTION_THROW = 4
tags.TAG_MINOR_TEMP_MUTATIONS = 5
tags.TAG_MINOR_AUTOINSCRIPTIONS = 6
tags.TAG_MINOR_UNCANCELLABLES = 7
tags.TAG_MINOR_DEEP_ABYSS = 8
tags.TAG_MINOR_COORD_SERIALIZER = 9
tags.TAG_MINOR_REMOVE_ABYSS_SEED = 10
tags.TAG_MINOR_REIFY_SUBVAULTS = 11
tags.TAG_MINOR_VEHUMET_SPELL_GIFT = 12
tags.TAG_MINOR_0_12 = 13
tags.TAG_MINOR_BATTLESPHERE_MID = 14
tags.TAG_MINOR_MALMUTATE = 15
tags.TAG_MINOR_VEHUMET_MULTI_GIFTS = 16
tags.TAG_MINOR_ADD_ABYSS_SEED = 17
tags.TAG_MINOR_COMPANION_LIST = 18
tags.TAG_MINOR_INCREMENTAL_RECALL = 19
tags.TAG_MINOR_GOD_GIFT = 20
tags.NUM_TAG_MINORS = 21
tags.TAG_MINOR_VERSION = tags.NUM_TAG_MINORS - 1
