/* Definitions for unrandom artefacts. */

/**********************************************************************
 * WARNING!
 *
 * This file is automatically generated. Do not edit this file directly;
 * instead edit art-data.txt to modify unrandart data, or util/art-data.pl
 * if this file is not being generated to your taste.
 *
 * If the unrandart_entry struct is changed or a new artefact property is
 * added to artefact_prop_type, then change art-data.pl so that the
 * art-data.h file it produces matches up with the new structure.
 *
 * Ignoring these warnings and editing this file directly will cause you
 * to be hunted down and eaten by dire tarantulas.
 **********************************************************************/

#ifndef art_data_h
#ifndef ART_FUNC_H
#error "art-func.h must be included before art-data.h"
#endif

#define art_data_h

/* UNRAND_DUMMY1 */
{
    "DUMMY UNRANDART 1", "DUMMY UNRANDART 1", NULL, 
    OBJ_UNASSIGNED, 250, 250, 250, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SINGING_SWORD */
{
    "Singing Sword", "Singing Sword", NULL, 
    OBJ_WEAPONS, WPN_LONG_SWORD, +7, +7, ETC_GOLD, 1200, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _SINGING_SWORD_equip, _SINGING_SWORD_unequip, _SINGING_SWORD_world_reacts, { NULL }, NULL, 
},

/* UNRAND_TROG */
{
    "Wrath of Trog", "Wrath of Trog", NULL, 
    OBJ_WEAPONS, WPN_BATTLEAXE, +3, +11, ETC_BLOOD, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ANTIMAGIC, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 50, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _TROG_equip, _TROG_unequip, NULL, { NULL }, NULL, 
},

/* UNRAND_VARIABILITY */
{
    "Mace of Variability", "Mace of Variability", NULL, 
    OBJ_WEAPONS, WPN_GREAT_MACE, 0, 0, ETC_RANDOM, 700, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_CHAOS, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, _VARIABILITY_world_reacts, { NULL }, NULL, 
},

/* UNRAND_PRUNE */
{
    "Glaive of Prune", "Glaive of Prune", NULL, 
    OBJ_WEAPONS, WPN_GLAIVE, +4, +12, MAGENTA, 1000, 
    UNRAND_FLAG_CHAOTIC, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _PRUNE_equip, NULL, _PRUNE_world_reacts, { NULL }, NULL, 
},

/* UNRAND_POWER */
{
    "Sword of Power", "Sword of Power", NULL, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, 0, 0, RED, 1000, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _POWER_equip, NULL, _POWER_world_reacts, { NULL }, NULL, 
},

/* UNRAND_OLGREB */
{
    "Staff of Olgreb", "Staff of Olgreb", NULL, 
    OBJ_WEAPONS, WPN_STAFF, 0, 0, ETC_POISON, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _OLGREB_equip, _OLGREB_unequip, _OLGREB_world_reacts, { _OLGREB_melee_effect }, _OLGREB_evoke, 
},

/* UNRAND_WUCAD_MU */
{
    "Staff of Wucad Mu", "Staff of Wucad Mu", NULL, 
    OBJ_WEAPONS, WPN_STAFF, +9, +9, ETC_MAGIC, 1000, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, _WUCAD_MU_evoke, 
},

/* UNRAND_VAMPIRES_TOOTH */
{
    "Vampire's Tooth", "Vampire's Tooth", NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +3, +4, ETC_BONE, 1000, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_VAMPIRICISM, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _VAMPIRES_TOOTH_equip, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_CURSES */
{
    "Scythe of Curses", "Scythe of Curses", NULL, 
    OBJ_WEAPONS, WPN_SCYTHE, +13, +13, ETC_DEATH, 800, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _CURSES_equip, NULL, _CURSES_world_reacts, { _CURSES_melee_effect }, NULL, 
},

/* UNRAND_TORMENT */
{
    "Sceptre of Torment", "Sceptre of Torment", NULL, 
    OBJ_WEAPONS, WPN_MACE, +7, +6, ETC_GOLD, 1200, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _TORMENT_equip, NULL, _TORMENT_world_reacts, { _TORMENT_melee_effect }, NULL, 
},

/* UNRAND_ZONGULDROK */
{
    "Sword of Zonguldrok", "Sword of Zonguldrok", NULL, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, +9, +9, ETC_BONE, 1250, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL | UNRAND_FLAG_CORPSE_VIOLATING, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _ZONGULDROK_equip, NULL, _ZONGULDROK_world_reacts, { _ZONGULDROK_melee_effect }, NULL, 
},

/* UNRAND_CEREBOV */
{
    "Sword of Cerebov", "great serpentine sword", "flamberge", 
    OBJ_WEAPONS, WPN_GREAT_SWORD, +6, +6, ETC_FIRE, 2000, 
    UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _CEREBOV_melee_effect }, NULL, 
},

/* UNRAND_DISPATER */
{
    "Staff of Dispater", "golden staff", NULL, 
    OBJ_WEAPONS, WPN_STAFF, +4, +4, ETC_GOLD, 1200, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _DISPATER_melee_effect }, _DISPATER_evoke, 
},

/* UNRAND_ASMODEUS */
{
    "Sceptre of Asmodeus", "ruby sceptre", NULL, 
    OBJ_WEAPONS, WPN_STAFF, +7, +7, ETC_BLOOD, 1500, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _ASMODEUS_melee_effect }, _ASMODEUS_evoke, 
},

/* UNRAND_FAERIE */
{
    "faerie dragon armour", "faerie dragon armour", NULL, 
    OBJ_ARMOUR, ARM_MOTTLED_DRAGON_ARMOUR, +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NOGEN | UNRAND_FLAG_UNIDED, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BLOODBANE */
{
    "demon blade \"Bloodbane\"", "demon blade \"Bloodbane\"", NULL, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, +7, +8, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 9, 0, 
        0, 0, 0, 0, -20, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FLAMING_DEATH */
{
    "scimitar of Flaming Death", "scimitar of Flaming Death", NULL, 
    OBJ_WEAPONS, WPN_SCIMITAR, +7, +5, ETC_FIRE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        2, -1, 0, 1, 0, 20, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BRILLIANCE */
{
    "mace of Brilliance", "mace of Brilliance", NULL, 
    OBJ_WEAPONS, WPN_MACE, +5, +5, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 5, 0, 0, 5, 0, 
        0, 0, 0, 0, 1, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -20, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _BRILLIANCE_equip, _BRILLIANCE_unequip, NULL, { NULL }, NULL, 
},

/* UNRAND_LEECH */
{
    "demon blade \"Leech\"", "demon blade \"Leech\"", NULL, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, +13, +4, MAGENTA, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VAMPIRICISM, 0, -1, -1, -1, -1, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_CHILLY_DEATH */
{
    "dagger of Chilly Death", "dagger of Chilly Death", NULL, 
    OBJ_WEAPONS, WPN_DAGGER, +5, +7, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        -1, 2, 0, 1, 0, 20, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_MORG */
{
    "dagger \"Morg\"", "dagger \"Morg\"", NULL, 
    OBJ_WEAPONS, WPN_DAGGER, -1, +4, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PAIN, 0, 0, 0, 5, 0, 
        0, 0, 0, 0, 0, 30, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FINISHER */
{
    "scythe \"Finisher\"", "scythe \"Finisher\"", NULL, 
    OBJ_WEAPONS, WPN_SCYTHE, +3, +5, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_PUNK */
{
    "sling \"Punk\"", "sling \"Punk\"", NULL, 
    OBJ_WEAPONS, WPN_SLING, +9, +12, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FROST, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_KRISHNA */
{
    "bow of Krishna \"Sharnga\"", "bow of Krishna \"Sharnga\"", NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +8, +8, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SKULLCRUSHER */
{
    "giant club \"Skullcrusher\"", "giant club \"Skullcrusher\"", NULL, 
    OBJ_WEAPONS, WPN_GIANT_CLUB, +0, +5, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 5, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_GUARD */
{
    "glaive of the Guard", "glaive of the Guard", NULL, 
    OBJ_WEAPONS, WPN_GLAIVE, +5, +8, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 5, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_JIHAD */
{
    "sword of Jihad", "sword of Jihad", NULL, 
    OBJ_WEAPONS, WPN_EUDEMON_BLADE, +12, +10, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 0, 3, 0, 0, 0, 
        0, 0, 0, 0, 1, 20, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 
        0, 0, 0, 0, -50, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_HELLFIRE */
{
    "crossbow \"Hellfire\"", "crossbow \"Hellfire\"", NULL, 
    OBJ_WEAPONS, WPN_CROSSBOW, +6, +9, ETC_FIRE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAME, 0, 0, 0, 0, 0, 
        2, -1, 0, 0, 0, 40, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DOOM_KNIGHT */
{
    "sword of the Doom Knight", "sword of the Doom Knight", NULL, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, +13, +13, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PAIN, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 50, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_EOS */
{
    "morningstar \"Eos\"", "morningstar \"Eos\"", NULL, 
    OBJ_WEAPONS, WPN_MORNINGSTAR, +11, +11, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BOTONO */
{
    "spear of the Botono", "spear of the Botono", NULL, 
    OBJ_WEAPONS, WPN_SPEAR, +2, +10, ETC_UNHOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, -6, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_OCTOPUS_KING */
{
    "trident of the Octopus King", "trident of the Octopus King", NULL, 
    OBJ_WEAPONS, WPN_TRIDENT, +10, +4, ETC_WATER, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 1, 1, 0, 50, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ARGA */
{
    "mithril axe \"Arga\"", "mithril axe \"Arga\"", NULL, 
    OBJ_WEAPONS, WPN_WAR_AXE, +10, +6, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 2, 0, 0, 
        0, 0, 0, 0, 0, 30, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ELEMENTAL_STAFF */
{
    "Elemental Staff", "Elemental Staff", NULL, 
    OBJ_WEAPONS, WPN_STAFF, +3, +1, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PROTECTION, 0, 0, 0, 0, 0, 
        2, 2, 0, 0, 0, 60, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SNIPER */
{
    "crossbow \"Sniper\"", "crossbow \"Sniper\"", NULL, 
    OBJ_WEAPONS, WPN_CROSSBOW, +10, +0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_PIERCER */
{
    "longbow \"Piercer\"", "longbow \"Piercer\"", NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +2, +10, CYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, -2, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BLOWGUN_ASSASSIN */
{
    "blowgun of the Assassin", "blowgun of the Assassin", NULL, 
    OBJ_WEAPONS, WPN_BLOWGUN, +6, +6, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 60, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_WYRMBANE */
{
    "lance \"Wyrmbane\"", "lance \"Wyrmbane\"", "lance", 
    OBJ_WEAPONS, WPN_SPEAR, +9, +6, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_DRAGON_SLAYING, 5, 0, 0, 0, 0, 
        1, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +2, 
        0, 0, 
        
    },
    _WYRMBANE_equip, NULL, NULL, { _WYRMBANE_melee_effect }, NULL, 
},

/* UNRAND_SPRIGGANS_KNIFE */
{
    "Spriggan's Knife", "Spriggan's Knife", "knife", 
    OBJ_WEAPONS, WPN_DAGGER, +4, +10, LIGHTCYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 4, 0, 0, 4, 
        0, 0, 0, 0, 0, 20, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 50, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_PLUTONIUM_SWORD */
{
    "plutonium sword", "plutonium sword", NULL, 
    OBJ_WEAPONS, WPN_TRIPLE_SWORD, +12, +16, ETC_RANDOM, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, -20, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _PLUTONIUM_SWORD_melee_effect }, NULL, 
},

/* UNRAND_UNDEADHUNTER */
{
    "great mace \"Undeadhunter\"", "great mace \"Undeadhunter\"", NULL, 
    OBJ_WEAPONS, WPN_GREAT_MACE, +7, +7, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _UNDEADHUNTER_melee_effect }, NULL, 
},

/* UNRAND_SNAKEBITE */
{
    "whip \"Snakebite\"", "whip \"Snakebite\"", NULL, 
    OBJ_WEAPONS, WPN_WHIP, +5, +10, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ACCURACY */
{
    "knife of Accuracy", "knife of Accuracy", "knife", 
    OBJ_WEAPONS, WPN_DAGGER, +27, -1, LIGHTCYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_CRYSTAL_SPEAR */
{
    "Lehudib's crystal spear", "Lehudib's crystal spear", NULL, 
    OBJ_WEAPONS, WPN_SPEAR, +6, +6, GREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_RETURNING, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_CAPTAINS_CUTLASS */
{
    "captain's cutlass", "captain's cutlass", "cutlass", 
    OBJ_WEAPONS, WPN_SABRE, +6, +7, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, -1, +2, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_STORM_BOW */
{
    "storm bow", "storm bow", NULL, 
    OBJ_WEAPONS, WPN_LONGBOW, +8, +8, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, _STORM_BOW_world_reacts, { NULL }, NULL, 
},

/* UNRAND_IGNORANCE */
{
    "large shield of Ignorance", "large shield of Ignorance", NULL, 
    OBJ_ARMOUR, ARM_LARGE_SHIELD, +8, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 2, 2, 0, -6, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_AUGMENTATION */
{
    "robe of Augmentation", "robe of Augmentation", NULL, 
    OBJ_ARMOUR, ARM_ROBE, +4, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 4, 4, 4, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_THIEF */
{
    "cloak of the Thief", "cloak of the Thief", NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +2, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, -3, 0, 60, 0, 
        0, 0, 0, 0, 0, 
        0, 1, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BULLSEYE */
{
    "shield \"Bullseye\"", "shield \"Bullseye\"", NULL, 
    OBJ_ARMOUR, ARM_SHIELD, +15, 0, RED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, -5, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DYROVEPREVA */
{
    "crown of Dyrovepreva", "crown of Dyrovepreva", NULL, 
    OBJ_ARMOUR, ARM_CAP, +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 2, 0, 
        0, 0, 1, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BEAR_SPIRIT */
{
    "hat of the Bear Spirit", "hat of the Bear Spirit", NULL, 
    OBJ_ARMOUR, ARM_CAP, +2, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 50, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_MISFORTUNE */
{
    "robe of Misfortune", "robe of Misfortune", NULL, 
    OBJ_ARMOUR, ARM_ROBE, -5, 0, MAGENTA, 0, 
    UNRAND_FLAG_RANDAPP | UNRAND_FLAG_UNIDED, 
    {
        SPARM_NORMAL, 0, -4, -2, -2, -2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 1, 0, 0, 0, 
        1, 0, 0, 1, -80, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FLASH */
{
    "cloak of Flash", "cloak of Flash", NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +3, 0, ETC_FLASH, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BOOTS_ASSASSIN */
{
    "boots of the Assassin", "boots of the Assassin", NULL, 
    OBJ_ARMOUR, ARM_BOOTS, +2, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 80, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_LEAR */
{
    "Lear's chain mail", "Lear's chain mail", NULL, 
    OBJ_ARMOUR, ARM_CHAIN_MAIL, -1, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_RANDAPP | UNRAND_FLAG_UNIDED, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, -3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 
        0, 0, 0, -1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ZHOR */
{
    "skin of Zhor", "skin of Zhor", NULL, 
    OBJ_ARMOUR, ARM_ANIMAL_SKIN, +4, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 2, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SALAMANDER */
{
    "salamander hide armour", "salamander hide armour", NULL, 
    OBJ_ARMOUR, ARM_LEATHER_ARMOUR, +3, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        2, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_WAR */
{
    "gauntlets of War", "gauntlets of War", NULL, 
    OBJ_ARMOUR, ARM_GLOVES, +3, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 5, 5, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_RESISTANCE */
{
    "shield of Resistance", "shield of Resistance", NULL, 
    OBJ_ARMOUR, ARM_SHIELD, +5, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        1, 1, 0, 0, 0, 40, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FOLLY */
{
    "robe of Folly", "robe of Folly", NULL, 
    OBJ_ARMOUR, ARM_ROBE, 3, 0, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 5, 0, 
        0, 0, 0, 0, 0, -100, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 3, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_MAXWELL */
{
    "Maxwell's patent armour", "Maxwell's patent armour", NULL, 
    OBJ_ARMOUR, ARM_PLATE_ARMOUR, +15, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_PRESERVATION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 50, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 
        0, 0, 0, -1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DRAGONMASK */
{
    "mask of the Dragon", "mask of the Dragon", NULL, 
    OBJ_ARMOUR, ARM_CAP, 0, 0, ETC_SHIMMER_BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 40, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 3, 3, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_NIGHT */
{
    "robe of Night", "robe of Night", NULL, 
    OBJ_ARMOUR, ARM_ROBE, +4, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 30, 
        1, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 50, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _NIGHT_equip, _NIGHT_unequip, NULL, { NULL }, NULL, 
},

/* UNRAND_DRAGON_KING */
{
    "armour of the Dragon King", "armour of the Dragon King", NULL, 
    OBJ_ARMOUR, ARM_GOLD_DRAGON_ARMOUR, +9, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 50, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ALCHEMIST */
{
    "hat of the Alchemist", "hat of the Alchemist", NULL, 
    OBJ_ARMOUR, ARM_WIZARD_HAT, +2, 0, MAGENTA, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        1, 1, 1, 0, 0, 30, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FENCERS_GLOVES */
{
    "fencer's gloves", "fencer's gloves", NULL, 
    OBJ_ARMOUR, ARM_GLOVES, +2, 0, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 3, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 8, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_STARLIGHT */
{
    "cloak of Starlight", "cloak of Starlight", NULL, 
    OBJ_ARMOUR, ARM_CLOAK, 0, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 1, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -30, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_RATSKIN_CLOAK */
{
    "ratskin cloak", "ratskin cloak", NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +1, 0, ETC_BEOGH, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, -1, -1, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_GONG */
{
    "shield of the gong", "shield of the gong", NULL, 
    OBJ_ARMOUR, ARM_SHIELD, +6, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 1, 50, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _GONG_melee_effect }, NULL, 
},

/* UNRAND_AIR */
{
    "amulet of the Air", "amulet of the Air", NULL, 
    OBJ_JEWELLERY, AMU_INACCURACY, 0, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 5, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SHADOWS */
{
    "ring of Shadows", "ring of Shadows", NULL, 
    OBJ_JEWELLERY, RING_INVISIBILITY, 0, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, -4, 0, 0, 40, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_CEKUGOB */
{
    "amulet of Cekugob", "amulet of Cekugob", NULL, 
    OBJ_JEWELLERY, AMU_WARDING, 0, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 1, 1, 0, 0, 0, 
        0, 0, 1, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_FOUR_WINDS */
{
    "amulet of the Four Winds", "amulet of the Four Winds", NULL, 
    OBJ_JEWELLERY, AMU_CLARITY, 0, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 100, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BLOODLUST */
{
    "necklace of Bloodlust", "necklace of Bloodlust", NULL, 
    OBJ_JEWELLERY, AMU_RAGE, 0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 2, -2, 0, 
        0, 0, 0, 0, 0, 30, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 9, 0, 
        0, 0, 5, 3, -20, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SHAOLIN */
{
    "ring of Shaolin", "ring of Shaolin", NULL, 
    OBJ_JEWELLERY, RING_EVASION, +8, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_ROBUSTNESS */
{
    "ring of Robustness", "ring of Robustness", NULL, 
    OBJ_JEWELLERY, RING_PROTECTION, +8, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_MAGE */
{
    "ring of the Mage", "ring of the Mage", NULL, 
    OBJ_JEWELLERY, RING_WIZARDRY, 0, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 50, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_SHIELDING */
{
    "brooch of Shielding", "brooch of Shielding", NULL, 
    OBJ_JEWELLERY, AMU_WARDING, 0, 0, ETC_MAGIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 4, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_RCLOUDS */
{
    "robe of Clouds", "robe of Clouds", NULL, 
    OBJ_ARMOUR, ARM_ROBE, +3, 0, ETC_MIST, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _RCLOUDS_equip, NULL, _RCLOUDS_world_reacts, { NULL }, NULL, 
},

/* UNRAND_PONDERING */
{
    "hat of Pondering", "hat of Pondering", NULL, 
    OBJ_ARMOUR, ARM_WIZARD_HAT, +3, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, +5, 0, 
        0, 0, 0, 0, 0, 30, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +10, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DEMON_AXE */
{
    "obsidian axe", "obsidian axe", NULL, 
    OBJ_WEAPONS, WPN_BROAD_AXE, +12, +15, ETC_UNHOLY, 0, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL, 
    {
        SPWPN_VORPAL, 0, 0, +3, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, _DEMON_AXE_unequip, _DEMON_AXE_world_reacts, { _DEMON_AXE_melee_effect }, NULL, 
},

/* UNRAND_LIGHTNING_SCALES */
{
    "lightning scales", "lightning scales", NULL, 
    OBJ_ARMOUR, ARM_NAGA_BARDING, +3, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_RUNNING, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_BLACK_KNIGHT_HORSE */
{
    "Black Knight's horse barding", "Black Knight's horse barding", NULL, 
    OBJ_ARMOUR, ARM_CENTAUR_BARDING, +10, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_EVIL, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, -2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, _BLACK_KNIGHT_HORSE_world_reacts, { NULL }, NULL, 
},

/* UNRAND_VITALITY */
{
    "ring of Vitality", "ring of Vitality", NULL, 
    OBJ_JEWELLERY, RING_REGENERATION, 0, 0, ETC_MUTAGENIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, +15, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_AUTUMN_KATANA */
{
    "autumn katana", "autumn katana", "katana", 
    OBJ_WEAPONS, WPN_LONG_SWORD, +8, +8, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VORPAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        -2, 0, 1, +2, +4, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DEVASTATOR */
{
    "shillelagh \"Devastator\"", "shillelagh \"Devastator\"", "shillelagh", 
    OBJ_WEAPONS, WPN_CLUB, +4, +8, WHITE, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +3, 
        0, 0, 
        
    },
    _DEVASTATOR_equip, NULL, NULL, { _DEVASTATOR_melee_effect }, NULL, 
},

/* UNRAND_DRAGONSKIN */
{
    "dragonskin cloak", "opalescent scaly cloak", NULL, 
    OBJ_ARMOUR, ARM_CLOAK, +4, 0, ETC_HEAL, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    _DRAGONSKIN_equip, _DRAGONSKIN_unequip, NULL, { NULL }, NULL, 
},

/* UNRAND_OCTOPUS_KING_RING */
{
    "ring of the Octopus King", "ring of the Octopus King", NULL, 
    OBJ_JEWELLERY, RING_HUNGER, 0, 0, ETC_WATER, 0, 
    UNRAND_FLAG_UNIDED, 
    {
        0, 1, 1, 1, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_WOE */
{
    "Axe of Woe", "Axe of Woe", NULL, 
    OBJ_WEAPONS, WPN_EXECUTIONERS_AXE, 0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { _WOE_melee_effect }, NULL, 
},

/* UNRAND_MILK_CHOCOLATE */
{
    "milk chocolate", "milk chocolate", NULL, 
    OBJ_JEWELLERY, AMU_STASIS, 0, 0, BROWN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        0, 0, 3, 3, 3, 3, 
        3, 3, 1, 1, 1, 100, 
        1, 1, 1, 1, 1, 0, 
        1, 0, 1, 100, 10, 
        1, 60, 60, 0, 100, 10, 
        0, 10, 1, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DARK_CHOCOLATE */
{
    "dark chocolate", "dark chocolate", NULL, 
    OBJ_JEWELLERY, AMU_RESIST_CORROSION, 0, 0, DARKGREY, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        0, 0, -3, -3, -3, -3, 
        -3, -3, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, -10, 
        0, -60, -60, 0, -100, -10, 
        0, -10, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

/* UNRAND_DUMMY2 */
{
    "DUMMY UNRANDART 2", "DUMMY UNRANDART 2", NULL, 
    OBJ_UNASSIGNED, 250, 250, 250, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 
        
    },
    NULL, NULL, NULL, { NULL }, NULL, 
},

#endif /* art_data_h */
